spring:
  application:
    name: spring-cloud-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:              ##Feign 自带熔断器的，默认是关闭
  hystrix:
    enabled: true
spring:
  zipkin:
    base-url: http://localhost:9411